from langgraph.graph import END, START, StateGraph

from graph_runtime.state import AgentState


def _load_context(state: AgentState) -> AgentState:
    state["plan"] = ["inspect schema", "generate read-only SQL", "summarize findings"]
    return state


def _write_answer(state: AgentState) -> AgentState:
    state["final_answer"] = "Scaffold response generated by graph runtime."
    return state


def build_graph():
    workflow = StateGraph(AgentState)
    workflow.add_node("load_context", _load_context)
    workflow.add_node("write_answer", _write_answer)
    workflow.add_edge(START, "load_context")
    workflow.add_edge("load_context", "write_answer")
    workflow.add_edge("write_answer", END)
    return workflow.compile()

