from pydantic import BaseModel, Field


class AnalysisTaskRequest(BaseModel):
    task_id: str = Field(..., description="Task identifier generated by Java")
    trace_id: str = Field(..., description="Trace identifier spanning Java and Python")
    tenant_id: str
    user_id: str
    question: str
    dataset_ids: list[str] = Field(default_factory=list)

